# Generated by Django 4.0.6 on 2022-07-11 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='creted',
            new_name='created',
        ),
    ]
